xxl:
  job:
    # 执行器通讯TOKEN [选填]
    # 1)非空时启用
    # 2)默认是一个 default_token, 如果未配置, 应该未空 (官网Bug https://github.com/xuxueli/xxl-job/issues/1951)
    access_token: default_token
    admin:
      # 调度中心部署跟地址 [选填]
      # 1) 如调度中心集群部署存在多个地址则用逗号分隔。
      # 2) 执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；
      # 3) 为空则关闭自动注册；
      # 4) 也就是我们访问 xxl-job
      address: http://127.0.0.1:9090/xxl-job-admin
    # 注册执行器
    executor:
      # 执行器 AppName [选填]
      # 1) 执行器心跳注册分组依据；
      # 2) 为空则关闭自动注册
      # 3) 这里我们使用官网默认提供的执行器 xxl-job-executor-sample 你可以新增或者修改
      appname: xxl-job-executor-sample
      # 执行器注册 [选填]：
      # 1) 优先使用该配置作为注册地址，
      # 2) 为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。
      # 3) 从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      # 执行器IP [选填]
      # 1) 默认为空表示自动获取IP，
      # 2) 多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；
      # 3) 地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      #       # 1) 小于等于0则自动获取；
      # 2) 默认端口为9999;
      # 3) 单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999
      # 执行器运行日志文件存储磁盘路径 [选填]
      # 1) 需要对该路径拥有读写权限；
      # 2) 为空则使用默认路径；
      logpath: ./data/applogs/xxl-job/jobhandler
      # 执行器日志文件保存天数 [选填]
      # 1) 过期日志自动清理;
      # 2) 限制值大于等于3时生效, 否则, 如-1, 关闭自动清理功能
      log_retention_days: 30
