include:
  - project: homelab/gitlab-ci-templates
    ref: main
    file: templates/k8s/java-pipeline.yml

variables:
  TP_RUN_BUILD: "true"
  TP_RUN_TEST: "false"
  TP_RUN_RELEASE: "false"
  TP_RUN_PAGES: "false"

  ## 构建参数
  TP_BUILD_IMAGE: ${DF_MAVEN_IMAGE}
  TP_MAVEN_OPTS: "-Dmaven.repo.local=${TP_RUNNER_BUILD_CACHE} --settings .mvn/settings.xml"
  TP_BUILD_SHELL: "mvn clean package ${TP_MAVEN_OPTS} -DskipTests -Pcoding"

  ## 单元测试参数
  TP_TEST_IMAGE: ${TP_BUILD_IMAGE}
  TP_JUNIT_REPORT_PATH: 'target/surefire-reports/TEST-*.xml'
  TP_TEST_SHELL: "mvn test ${TP_MAVEN_OPTS}"

  ## 发布制品参数 - by maven
  TP_MAVEN_DPLOY_SHELL: "mvn clean deploy ${TP_MAVEN_OPTS} -DskipTests \ 
                         -Pcoding,publish-artifactory \
                         -Dauto.release.enabled=false -Dauto.archetype.catalog.minio=false"

  ## 发布 pages - writerside
  TP_PAGES_TYPE: "writerside"
  TP_WRITERSIDE_INSTANCE: "Writerside/scaffold-std-demo"