include:
  - project: homelab/gitlab-ci-templates
    ref: main
    file: templates/java-pipeline.yml

variables:
  BUILD_SHELL: 'mvn clean package -DskipTests'
  CACHE_DIR: 'scaffold-std-demo-app/target'
