--- # log
debug: false
logging:
  file:
    path: ../logs/${spring.application.name}
  level:
    space.x9x.radp: debug
    space.x9x: debug
--- # database
spring:
  datasource:
    username: ENC(VDoSzyZ7jS/lvaBnAaIc3ePEo9bh6QEb)
    password: ENC(uvgZQKBNymDMjPilZgaRHAE4LEeSW1xj)