networks:
  local-network:
    driver: bridge

services:
  # 方式一: 如果使用传统的 zookeeper 模式
  zookeeper:
    image: zookeeper:3.9.0
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: yes
      TZ: Asia/Shanghai
    networks:
      - local-network